### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by kstrafe** [BourgondAries/elevators#1]
- [ ] Sending: Implement hashing of messages
- [ ] Receiving: Check the hash and unpack if correct, else throw it away
- [ ] Secure `fasl->s-exp` in `receive` by using an exception handler (it can fail if the byte string is corrupted)
- [ ] Filter messages based on newest message (Will need to add timestamp in send)
- [ ] Update lamps based on requests
- [ ] Poll button presses
- [ ] Compute which elevator will take an action
- [ ] Motor integrity checking
